# DigiHealth Lamp Configuration
sensors:
  zph:
    port: "/dev/serial0"
    baudrate: 9600
    command: [255, 1, 134, 0, 0, 0, 0, 0, 121]
  light:
    i2c_bus: 1
    address: 0x23
  door:
    gpio_pin: 18
  window:
    gpio_pin: 17
  microphone:
    enabled: true
    device_index: 1        # USB PnP Sound Device (hw:4,0)
    output_device_index: 1 # bcm2835 Headphones - jack output (hw:2,0)


processors:
  iaqi:
    enabled: true
  circadian:
    enabled: true
  audio_comfort:
    enabled: true
    check_duration: 10      
    comfort_duration: 300
    tolerance_threshold: 45.0
    critical_threshold: 55.0

actuators:
  neopixel:
    enabled: true  #non presente
    pin: 12
    num_pixels: 144
    iaqi_range: [0, 79]
    circadian_range: [80, 143]
  shelly:
    enabled: false
    # Aggiungere qui tutte le Shelly presenti in rete.
    # Solo quelle con enabled: true verranno comandate.
    devices:
      - name: "Lampada Scrivania"
        ip: "192.168.1.191"
        enabled: true
      # - name: "Lampada Comodino"
      #   ip: "192.168.1.192"
      #   enabled: false

communicator:
  telegraf:
    enabled: true
    measurement: "ZPHSensor_sensore"
    tags:
      sensor: "ZPHS01B"
      host: "raspberry01"
  ipc:
    method: "sqlite"  # or "redis"
    db_path: "/tmp/digihealth.db"

web:
  enabled: true  
  host: "0.0.0.0"  #192.168.0.104
  port: 5000

logging:
  level: "INFO"
  file: "/var/log/digihealth-lamp.log"
